[package]
name = "gst-plugin-nvargustime"
description = "support for timestamps from nvarguscamersrc"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2021"
rust-version = "1.76"
repository = "https://github.com/strawlab/strand-braid"

[lib]
name = "gstrsnvargustime"
crate-type = ["cdylib", "rlib", "staticlib"]
path = "src/lib.rs"

[dependencies]
libc = "0.2"
glib = "0.10"
glib-sys = "0.10"
gobject-sys = "0.10"
gstreamer = "0.16"
gstreamer-sys = "0.9"
gstreamer-base = "0.16"
gstreamer-video = "0.16"
lazy_static = "1.0"

[build-dependencies]
gst-plugin-version-helper = "0.7.5"
